version: '3.8'

services:
  scholar-service:
    build: 
      context: ./scholar_to_bibtex
      dockerfile: Dockerfile
    environment:
      - SERPAPI_KEY=${SERPAPI_KEY}
      - SCHOLAR_PROFILE_URL=${SCHOLAR_PROFILE_URL}
      - FLASK_ENV=production
      - OUTPUT_DIR=/app/data
    volumes:
      - bib_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  embed-service:
    build:
      context: ./Bib-File-to-Embed
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BIB_FILE_DIR=/app/data
    volumes:
      - bib_data:/app/data
    depends_on:
      - scholar-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

volumes:
  bib_data:
    name: bib_data

networks:
  app-network:
    name: app-network 